### ISSUE TITLE
Exiting nano will print "[?2004h[?2004l" to console

### ISSUE THREAD

**Issue by dfs-** [lhmouse/nano-win#13]
Exiting nano will print the above text to console. 
Older versions, tested with v3.1-68-ga86a9b1a will not do so.

You can see a screenshot here: https://imgur.com/a/UWVc7XX

System specs:
Windows 10 x64 Version 1909 (Build 18363.778)

**Comment by lhmouse** [comment]
f705a9674b2ad75702f2c1e8c989558d45a7d243

**Comment by lhmouse** [comment]
Fixed in <https://files.lhmouse.com/nano-win/nano-win_8920_v4.9-168-gccf508e2.7z>.

**Comment by dfs-** [comment]
Unfortunately, the issue still persists, even with the new build.

**Comment by lhmouse** [comment]
Please check the version number in the upper left corner to make sure that you have updated the executable.

https://github.com/lhmouse/nano-win/commit/ccf508e2000c1c33b4cda36a4f1d697d8b82257e#diff-288cca21deb5dca702f247ebab4b7073L1213

**Comment by dfs-** [comment]
Hi lhmouse, the top left corner states "v4.9-4-g5929ad7c". Is this the correct version?

**Comment by lhmouse** [comment]
The lastest build is `v4.9-168-gccf508e2`.

**Comment by dfs-** [comment]
Thanks for bearing with me. The issue now doesn't appear, but the top status bar still shows another GIT short hash: v4.9-168-**gae369e71**

**Comment by lhmouse** [comment]
The `168` in the version string denotes it was 168 commits ahead of the v4.9 tag, so as long as this number is correct, it shouldn't matter. Probably it was caused by another rebase operation.
